//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.04.02 at 02:51:45 PM MSK 
//

package by.training.task4.entity;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.example.gems package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Pearl_QNAME = new QName("http://www.example.com/gems", "Pearl");
    private final static QName _AbstractGem_QNAME = new QName("http://www.example.com/gems", "AbstractGem");
    private final static QName _Emerald_QNAME = new QName("http://www.example.com/gems", "Emerald");
    private final static QName _Diamond_QNAME = new QName("http://www.example.com/gems", "Diamond");
    private final static QName _AbstractGemPreciousness_QNAME = new QName("http://www.example.com/gems", "preciousness");
    private final static QName _AbstractGemWeight_QNAME = new QName("http://www.example.com/gems", "weight");
    private final static QName _AbstractGemName_QNAME = new QName("http://www.example.com/gems", "name");
    private final static QName _AbstractGemGemArrival_QNAME = new QName("http://www.example.com/gems", "gemArrival");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.example.gems
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Pearl }
     * 
     */
    public Pearl createPearl() {
        return new Pearl();
    }

    /**
     * Create an instance of {@link AbstractGem }
     * 
     */
    public AbstractGem createAbstractGem() {
        return new AbstractGem();
    }

    /**
     * Create an instance of {@link Gems }
     * 
     */
    public Gems createGems() {
        return new Gems();
    }

    /**
     * Create an instance of {@link Emerald }
     * 
     */
    public Emerald createEmerald() {
        return new Emerald();
    }

    /**
     * Create an instance of {@link Diamond }
     * 
     */
    public Diamond createDiamond() {
        return new Diamond();
    }

    /**
     * Create an instance of {@link Weight }
     * 
     */
    public Weight createWeight() {
        return new Weight();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Pearl }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.example.com/gems", name = "Pearl", substitutionHeadNamespace = "http://www.example.com/gems", substitutionHeadName = "AbstractGem")
    public JAXBElement<Pearl> createPearl(Pearl value) {
        return new JAXBElement<Pearl>(_Pearl_QNAME, Pearl.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AbstractGem }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.example.com/gems", name = "AbstractGem")
    public JAXBElement<AbstractGem> createAbstractGem(AbstractGem value) {
        return new JAXBElement<AbstractGem>(_AbstractGem_QNAME, AbstractGem.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Emerald }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.example.com/gems", name = "Emerald", substitutionHeadNamespace = "http://www.example.com/gems", substitutionHeadName = "AbstractGem")
    public JAXBElement<Emerald> createEmerald(Emerald value) {
        return new JAXBElement<Emerald>(_Emerald_QNAME, Emerald.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Diamond }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.example.com/gems", name = "Diamond", substitutionHeadNamespace = "http://www.example.com/gems", substitutionHeadName = "AbstractGem")
    public JAXBElement<Diamond> createDiamond(Diamond value) {
        return new JAXBElement<Diamond>(_Diamond_QNAME, Diamond.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Preciousness }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.example.com/gems", name = "preciousness", scope = AbstractGem.class)
    public JAXBElement<Preciousness> createAbstractGemPreciousness(Preciousness value) {
        return new JAXBElement<Preciousness>(_AbstractGemPreciousness_QNAME, Preciousness.class, AbstractGem.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Weight }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.example.com/gems", name = "weight", scope = AbstractGem.class)
    public JAXBElement<Weight> createAbstractGemWeight(Weight value) {
        return new JAXBElement<Weight>(_AbstractGemWeight_QNAME, Weight.class, AbstractGem.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.example.com/gems", name = "name", scope = AbstractGem.class)
    public JAXBElement<String> createAbstractGemName(String value) {
        return new JAXBElement<String>(_AbstractGemName_QNAME, String.class, AbstractGem.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.example.com/gems", name = "gemArrival", scope = AbstractGem.class)
    public JAXBElement<XMLGregorianCalendar> createAbstractGemGemArrival(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_AbstractGemGemArrival_QNAME, XMLGregorianCalendar.class, AbstractGem.class, value);
    }

}
